server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=security
    username: postgres
    password: Postgres

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false