spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=photos&tableName=photo_meta_data,photo
    username: postgres
    password: Postgres
  data:
    mongodb:
      authentication-database: photo_db
      database: photo_db
      port: 27017
      host: localhost

base-url: http://127.0.0.1:8083/api/v1/photo/
